### ISSUE TITLE
Blurre brukernavn

### ISSUE THREAD

**Issue by kariesta** [devilry/devilry-django#1140]
Når jeg sitter på universitetet og retter hender det at noen går forbi, derfor har jeg brukt stylebot i chorme for å legge på følgende css til oversikt over innleveringer:
```css
.devilry-user-verbose-inline-fullname, .devilry-user-verbose-inline-shortname {
    -webkit-filter: blur(5px) grayscale(1);
    /* Safari 6.0 - 9.0 */
    filter: blur(5px) grayscale(1);
}
.devilry-user-verbose-inline-shortname:hover {
    -webkit-filter: blur(0px);
    /* Safari 6.0 - 9.0 */
    filter: blur(0px);
}
```
Tenker dette kan være fint å ha på alle steder med andres brukernavn, eller hvertfall fult navn.  Sikkert lurt å kunne deaktivere iblandt også.
